USE ucode_web;

CREATE TABLE IF NOT EXISTS powers(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name TEXT,
    type ENUM('attack', 'defense') NOT NULL,
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS heroes_powers(
    hero_id INT UNSIGNED NOT NULL,
    power_id INT UNSIGNED NOT NULL,    
    power_points INT UNSIGNED NOT NULL,
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS races(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name TEXT,
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS teams(
    id INT(6) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    name TEXT,
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS heroes_teams(
    hero_id INT UNSIGNED NOT NULL,
    teams_id INT UNSIGNED NOT NULL,
    FOREIGN KEY (hero_id)  REFERENCES heroes(id) ON DELETE CASCADE
);
